import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Upcoming from '@/web/movies/Upcoming'
import Series from '@/web/movies/Series'
import Actors from '@/web/actors/Actors'
import Genres from '@/web/movies/Genres'
import Index from '@/web/movies'
import Popular from '@/web/movies/Popular'
import Carousel from '@/Layout/Carousel'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Carousel />
        <Popular />
        <Index page={1} title='Ancient Movies'/>
        <Upcoming />
        <Series />
        <Index page={3} title='More Ancient Movies'/>
        <Actors />
        <Genres />
        <Index page={1000} title='1920s Movies'/>
      </main>
    </>
  )
}
